### ISSUE TITLE
tbdex-ts typescript release feature checklist

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/tbdex-rs#127]
tbdex-ts release feature checklist

#### `tbdex-ts`
- [ ] **Feature Parity And Full Tbdex Feature Set**
- [ ] **Test Vectors**
  - [ ] **Fix quote and orderinstructions**
  - [ ] **Generate and signing and signature validation**
- [ ] **Examples**
  - [ ] **PFI Hosted Service**
  - [ ] **Wallet**
  - [ ] **(Optional) create own example repo**
- [ ] **README updates**
- [ ] **In-line code documentation**
- [ ] **typedoc or other auto generated ts docs**
- [ ] **Artifact publishing**
  - [ ] **Npm Account Setup**
  - [ ] **Npm Publishing**
  - [ ] **Npm Docs**
- [ ] **FOSSA Scanning**
  - [ ] License
  - [ ] Security
- [ ] **CodeCov (test coverage)**
- [ ] **CodeQL (Static analysis)**
